### PR TITLE
Image error of user on blog page done

### PR DESCRIPTION
**Pull request by nooras**
# Related Issuse or bug
  - Image of user or default image is not coming on site

Fixes: #126

# Proposed Changes
 - Resolved the image error

# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **imageerror** | **updated screenshot **|

### CODE REVIEW

**Comment by nooras** [comment]
Checkout PR issue resolved @harsh-9in @SKAUL05  & @Kajol-Kumari

**Comment by harsh-9in** [comment]
@SKAUL05  plz review it.

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@nooras can you please remove the image files as i don't think those are required for this PR.

**Comment by nooras** [comment]
> @nooras can you please remove the image files as i don't think those are required for this PR.

Removed @Kajol-Kumari

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :)

**Pull request merged**
