### PR TITLE
Enhanced edit profile modal #91

### PR DESCRIPTION
**Pull request by kritikaparmar-programmer**
Fixes: #91 

# Proposed Changes
 - Enhanced Edit profile modal
 

# Screenshots
changes

### CODE REVIEW

**Comment by kritikaparmar-programmer** [comment]
Hey @Kajol-Kumari take a look at the changes..😊

**Comment by Kajol-Kumari** [comment]
Hey @kritikaparmar-programmer cann we remove the `image` text from the model as it seems unnecessary

**Comment by kritikaparmar-programmer** [comment]
Hey @Kajol-Kumari , I tried removing it but it seems it comes with the form..If its not what I think can you please suggest me an idea?

**Comment by kritikaparmar-programmer** [comment]
Hey @Kajol-Kumari any reviews???

**Comment by kritikaparmar-programmer** [comment]
Hey @harsh-9in , take a look at this edit ..

**Pull request merged**
