### PR TITLE
fix: requirements.txt file

### PR DESCRIPTION
**Pull request by SubhradeepSS**
# Related Issuse or bug
  - requirements.txt file

Fixes: #211 

# Proposed Changes
 - Included all the pip packages to the `requirements.txt` file so as to successfully run the project.
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot** | **updated screenshot **|

### CODE REVIEW

**Review by harsh-9in — COMMENTED** [review]
What changes you did? as it is showing binary fille not shown

**Comment by SubhradeepSS** [comment]
> 
> 
> What changes you did? as it is showing binary fille not shown

Earlier the requirements.txt file didn't had all the packages required to run the project, i added all those

**Comment by SubhradeepSS** [comment]
@harsh-9in Also please increase my points(NWOC) for the merged PR - #216

**Comment by harsh-9in** [comment]
> @harsh-9in Also please increase my points(NWOC) for the merged PR - #216

I will update all those by today.

**Pull request closed without merging**
