### PR TITLE
logo_added

### PR DESCRIPTION
**Pull request by ritiksoni00**
#17 
image (25) - Copy
Black-Texture

### CODE REVIEW

**Comment by ritiksoni00** [comment]
@Kajol-Kumari  as you said ! sorry but im having issues with reverting and rebase of commit

**Comment by ritiksoni00** [comment]
@Kajol-Kumari Now!!

**Review by Kajol-Kumari — APPROVED** [review]
Thank you @ritiksoni00 for incorporating the changes. This can be merged now :)

**Comment by ritiksoni00** [comment]
You are so helpful @Kajol-Kumari  Thank you so much For Help

**Comment by ritiksoni00** [comment]
@Kajol-Kumari  Label ??

**Pull request merged**
