### PR TITLE
Added Community_Extended page

### PR DESCRIPTION
**Pull request by Akshi149**
Added Community (extended) page

Fixes: #115 
  
# Screenshots

ui

### CODE REVIEW

**Comment by Akshi149** [comment]
@harsh-9in @Swarnimashukla @Kajol-Kumari please have a look over it.

**Review by harsh-9in — COMMENTED** [review]
Looks good. What you opinion @Swarnimashukla @Kajol-Kumari ?

**Comment by Swarnimashukla** [comment]
Yes it looks good to me 👍

**Review by Kajol-Kumari — APPROVED** [review]
Nice work! @Akshi149 LGTM :)

**Pull request merged**
