### PR TITLE
Created post_details.html 

### LINKED ISSUE #13: A seperate page for each post
Each title of post on home page directs to a new page containing details of that post

### PR DESCRIPTION
**Pull request by Joshitha18**
Fixes #13 
When clicked on title of a post on home page, it'll be redirected to a new page containing post details 
working

### CODE REVIEW

**Comment by harsh-9in** [comment]
@SKAUL05 plz review this

**Comment by SKAUL05** [comment]
> @SKAUL05 plz review this

Sure assign me as reviewer.

**Comment by Joshitha18** [comment]
@Kajol-Kumari Added requested changes

**Comment by Kajol-Kumari** [comment]
Hey @Joshitha18 please resolve the conflict here otherwise we won't be able to merge it.

**Pull request closed without merging**
