### PR TITLE
Added Like button

### PR DESCRIPTION
**Pull request by AkM-2018**
# Related Issue or bug
  Feature - Like button added

Fixes: #24 

# Proposed Changes
 - Added a like button which is visible in the post details page
 
# Additional Info
  1. If the user is not logged in, he is redirected to the home page
  2. If he is logged in, he can like a post. Clicking again on the button will undo his like.
 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot** | **updated screenshot **|

like_btn

### CODE REVIEW

**Comment by AkM-2018** [comment]
@Kajol-Kumari, any changes??

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Please resolve the conflict. Rest functionality looks fine to me. But please check once that after you login via a different id, whether u r able to see the likes count or not.

**Comment by AkM-2018** [comment]
@Kajol-Kumari, I think I have messed up something to resolve the conflict. I did git merge and some other things and, now nothing seems to work. I'm thinking of deleting everything and cloning the updated repo and starting again(copy-paste). Can I put another pull request?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari, I think I have messed up something to resolve the conflict. I did git merge and some other things and, now nothing seems to work. I'm thinking of deleting everything and cloning the updated repo and starting again(copy-paste). Can I put another pull request?

Yes @AkM-2018 , you can close this one and open up a new PR for the same.

**Pull request closed without merging**
