### PR TITLE
Added IA and resolved multiple commit problem

### PR DESCRIPTION
**Pull request by shraddhavp**
#117 
  - To create  and IA

Fixes: #117 

# Proposed Changes
 - Added user flowchart for the website
 and solved multiple commit issue

 this is the added IA
IA_shraddhavp

### CODE REVIEW

**Comment by shraddhavp** [comment]
@Kajol-Kumari  and @Swarnimashukla   mam did the changes in PR please do check out

**Comment by shraddhavp** [comment]
@harsh-9in  sir can you please check out the PR  IA for the website

**Comment by harsh-9in** [comment]
Okk @shraddhavp  I will review it.

**Comment by Kajol-Kumari** [comment]
@shraddhavp can you please add the image in the PR description as we can't view the image binary file in here

**Comment by shraddhavp** [comment]
@harsh-9in  added sir

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :-1:

**Pull request merged**
