### PR TITLE
Bio field added in profile

### PR DESCRIPTION
**Pull request by nooras**
# Related Issuse or bug
  - Bio field added in profile section

Fixes: #127 

# Proposed Changes
 - In model bio field added
 - In UserProfileUpdateForm bio field added and init function added
 -In view editprofile updated
 
# Additional Info
  - One default image addded in media/admin/default.jpg for image handling.

 
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **Group 1 (3)** | **Bio**|

### CODE REVIEW

**Comment by nooras** [comment]
Checkout PR @harsh-9in @Kajol-Kumari @SKAUL05

**Comment by harsh-9in** [comment]
@SKAUL05  plz review pr.

**Review by Kajol-Kumari — APPROVED** [review]
Nice work! LGTM :+1:

**Comment by nooras** [comment]
Checkout PR Removed conflicts and some line of codes in profile view for login user post(Additional- some code already written in profile.html for posts). @harsh-9in @Kajol-Kumari 
Screenshot from 2020-09-23 19-48-18

**Comment by harsh-9in** [comment]
@nooras plz remove conflicts.

**Comment by nooras** [comment]
> @nooras plz remove conflicts.

Removed @harsh-9in

**Pull request merged**
