### PR TITLE
Added Dashboard code

### PR DESCRIPTION
**Pull request by shraddhavp**
#113 
  - Code Dashboard UI

Fixes: #113 

# Proposed Changes
 - Added Dashboard code
 
# Screenshots
Screen Recording 2020-09-15 at 02 26 40 49 PM

### CODE REVIEW

**Review by harsh-9in — COMMENTED** [review]
@shraddhavp plz add the photo or gif of the changes.

**Comment by shraddhavp** [comment]
added @harsh-9in  sir

**Comment by harsh-9in** [comment]
@swapniltripathi123  @Kajol-Kumari plz have a look.
Can we improve **your stats** part?

**Comment by shraddhavp** [comment]
@harsh-9in sir  any changes needed?

**Comment by Kajol-Kumari** [comment]
Hey @shraddhavp can you please try improving the `your stats` section as it seems quite off compared to the others. Maybe we can keep a little bit of spacing between the buttons and also the background color doesn't seems to o with the page.

**Comment by shraddhavp** [comment]
ya ok I will do it

**Comment by harsh-9in** [comment]
@shraddhavp try to get some good png in `your stats` part and make a proper margin between them and apply a good background.

**Comment by harsh-9in** [comment]
@shraddhavp  you can refer this link for dashboard related template.

**Comment by shraddhavp** [comment]
ok sir will try it out

**Comment by shraddhavp** [comment]
@harsh-9in sir   @Swarnimashukla  and @Kajol-Kumari  mam please look into this new dashboards designed let mw know if any changes
Screen Recording 2020-09-21 at 03 43 00 81 PM

**Comment by harsh-9in** [comment]
@shraddhavp It looks amazing.
@Kajol-Kumari @Swarnimashukla what's your opinion?

**Comment by Swarnimashukla** [comment]
Yes, I can see great improvement from previous work 
@shraddhavp good work 👍

**Pull request closed without merging**
