### PR TITLE
Add markdown styling

### PR DESCRIPTION
**Pull request by ManishShah120**
# Description of the feature
  - Added all the required options & tools that's present in Markdown Styling so that any non-tech user's can write blogs with ease.
  - Added extra plugin for uploading any image at any position of the Blog.
  - Added extra plugin for the category of **Coding** Blog-Posts with syntax highlighting feature.

# Additional Changes[Fixes]
 - Fixed the position and spacing of the buttons of Pagination.
 - Fixed a minor error which caused while updating any particular Posts.
 - Fixed the position issue of the _View Count_ & _Read Time_ which was not being displayed inline.

Fixes: #136
 
# GIF
MarkdownStyling

### CODE REVIEW

**Comment by ManishShah120** [comment]
Hello @Kajol-Kumari , Can you review this, and let me know the changes, if any I have to make for this PR to get merged.

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@ManishShah120 can we please remove jpg files from this PR as I don't think we need them

**Comment by Kajol-Kumari** [comment]
One additional note @ManishShah120 Please avoid doing changes other than required for resolving the assigned issue in a single PR. Kike I can see many changes including comment modification, pagination count change etc. It's good practice to open up a new PR for such enhacements or changes other than those required by the related issue.

**Comment by ManishShah120** [comment]
@Kajol-Kumari , I have removed the jpg's, which could be removed.


> One additional note @ManishShah120 Please avoid doing changes other than required for resolving the assigned issue in a single PR. Like I can see many changes including comment modification, pagination count change etc. It's good practice to open up a new PR for such enhacements or changes other than those required by the related issue.

Okay, I will definitely take care of these from next time.

**Comment by Kajol-Kumari** [comment]
@ManishShah120 I can still see gifs and jpg files in the PR. Ifthey are not require, please remove them.

**Comment by ManishShah120** [comment]
`_icons.png, icons_hidpi.png, dialog_sides.gif, dialog_sides.png, dialog_sides_rtl.png, mini.gif, spinner.gif, sprites.png, sprites_ie6.png, toolbar_start.gif_ `

Hey @Kajol-Kumari, If you are requesting to remove the above files, then this files can't be removed because these are the icons, of the ckeditor toolbar, Though If I refresh the page after deleting all these files then the positions of these icons **blanks out**. Except these files, I am not able to figure out any other images/gif's that you are requesting me to remove.

**Review by Kajol-Kumari — APPROVED** [review]
Please resolve the conflict and its good to go :)

**Comment by ManishShah120** [comment]
Hey @Kajol-Kumari, some of the present changes from the upstream repo are creating an issue in the home page UI beacuase of  some of the repetitive line of codes, due to which the home page is not loading. Can I solve that problem, because without solving these issue I will not be able to resolve the conflicts, or should I wait for this #151  PR to get merged.

**Comment by Kajol-Kumari** [comment]
@ManishShah120 please wait for the PR #151 to be merged.

**Comment by Kajol-Kumari** [comment]
@ManishShah120 please resolve the conflicts now so that It can be merged.

**Comment by ManishShah120** [comment]
@Kajol-Kumari, Done please have a look.

**Review by Kajol-Kumari — APPROVED** [review]
This can be merged now.

**Pull request merged**
