### PR TITLE
[Fixed] View Count Refresh Issue

### PR DESCRIPTION
**Pull request by ManishShah120**
# Related Issues or bug
  - The current view count feature required a refresh to get the updated value of the view count for any blog-posts.

Fixes: #144

# Proposed Changes
 - Added an ajax synchronization feature to update the count of the number of views of different blogs.
 
# Additional Info
  - Added an additional `URL`path for fetching/requesting the data of `viewcount` for each blogs.
  - Added a special function-based view in `views.py` fro returning the fetched data to the template in JSON format.
  
# GIF
FixRefreshIssue

### CODE REVIEW

**Comment by ManishShah120** [comment]
@harsh-9in , @Kajol-Kumari, please have a look. and let me know if there are any required additional changes I need to make for this PR to be able to get merged.

**Review by harsh-9in — COMMENTED** [review]
I think everything is working fine. @Kajol-Kumari what is your opinion.

**Comment by harsh-9in** [comment]
@ManishShah120 You have done a really great job :+1:

**Review by Kajol-Kumari — APPROVED** [review]
Looks Good to go :)

**Pull request merged**
