### PR TITLE
[Fixes #222] Updated README.md file

### LINKED ISSUE #222: Update readme.md and contribution.md
As we have updated the project setting that's why it requires to set configurations in .env file. To create .env file you can take reference from .env.example file. This thing is going to mention is contributing and readme file.

### PR DESCRIPTION
**Pull request by Vrindagupta6828**
# Related Issue or bug
  - had to mention about .env file
Fixes: #222

### CODE REVIEW

**Comment by Vrindagupta6828** [comment]
@harsh-9in Please review my pr

**Review by harsh-9in — APPROVED** [review]

**Comment by Vrindagupta6828** [comment]
@harsh-9in Please update my points

**Comment by harsh-9in** [comment]
https://docs.google.com/spreadsheets/d/1Am9XMyGuIUAezCe54hw9fK1DcLuws8O5WiKa2zOSf9w/edit?usp=sharing

**Comment by harsh-9in** [comment]
The points of today's issue/pr will be increased till tonight.

**Comment by harsh-9in** [comment]
> https://docs.google.com/spreadsheets/d/1Am9XMyGuIUAezCe54hw9fK1DcLuws8O5WiKa2zOSf9w/edit?usp=sharing

check if I have missed previous points.

**Comment by Vrindagupta6828** [comment]
previous points are ok only points of today's pr are missing. Thanks

**Comment by Vrindagupta6828** [comment]
@harsh-9in my score has not been updated please look into the matter.

**Pull request merged**
