### PR TITLE
made changes to blog/views.py

### PR DESCRIPTION
**Pull request by shraddhavp**
#93 
  - a bug to view profile

Fixes: #93 

# Proposed Changes
 - Made changes in blog/views.py file
 
# Additional Info
  - now able to see my profile after login
  
# Screenshots

 
Screen Recording 2020-08-28 at 05 44 22 43 PM

### CODE REVIEW

**Comment by Akshi149** [comment]
@shraddhavp the feature is to view the profile of other users and for the logged-in user they have to click on the profile so that edit option is also visible for them.

cc\. @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Hey @Akshi149 ideally, this feature shouldn't through any error if the blog creator tries to view his/her profile via that link( whiuch was happening). Moreover, we can just show the owner's profile there like we do for other users and if owner wants to edit his/her details they can do via `profile` section of the site.

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :)

**Comment by shraddhavp** [comment]
@harsh-9in  for this should i create another PR  as i am seeing it is containing multiple commits

**Pull request closed without merging**
