### PR TITLE
Ritik_soniLogo_added

### PR DESCRIPTION
**Pull request by ritiksoni00**
Black-Texture
image (25) - Copy

### CODE REVIEW

**Comment by ritiksoni00** [comment]
@Kajol-Kumari  sorry but,i try to update that one pull request but couldn't!

**Comment by ritiksoni00** [comment]
@Swarnimashukla ??

**Comment by Swarnimashukla** [comment]
@Kajol-Kumari  is location for this issue correct ? @ritiksoni00  have you created a separate folder with your name and all files

**Review by Swarnimashukla — APPROVED** [review]

**Comment by ritiksoni00** [comment]
yes!!

**Comment by ritiksoni00** [comment]
i tried will you re-view it

**Comment by Kajol-Kumari** [comment]
> i tried will you re-view it

@ritiksoni00 sorry but i can still see the readme changes in here. please remove it then only we would be able to merge it. You can refer [here](https://stackoverflow.com/questions/3334475/git-how-to-update-checkout-a-single-file-from-remote-origin-master ) for reverting the change for `readme.md`

**Comment by ritiksoni00** [comment]
Wait...ill make the another pr

**Pull request closed without merging**
