### PR TITLE
delete/update-feature--@Ahana001

### PR DESCRIPTION
**Pull request by Ahana001**
# Related Issuse or bug
  - Info about Issue or bug

Fixes: #14

# Proposed Changes
 - Info about changes Goes here
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

 
Screenshot (77)

Screenshot (78)

### CODE REVIEW

**Comment by Ahana001** [comment]
issue
#14

**Comment by harsh-9in** [comment]
@SKAUL05 plz review this :)

**Comment by Ahana001** [comment]
Hnet-image(3)

**Comment by harsh-9in** [comment]
@Ahana001 plz remove conflicts then it is good to go.

**Comment by Ahana001** [comment]
@SKAUL05 @harsh-9in  removed conflicts!!

**Pull request merged**
