### PR TITLE
Added toast messages in the base template

### PR DESCRIPTION
**Pull request by ymaheshwari1**
# Related Issuse or bug
To show toast messages to the users

Fixes: #61

# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 | Mozilla-Firefox-2020-08-23-15-09|

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@ymaheshwari1 can we please put the toast as a separate template and just pass the test message to be displayed in it. This way we can use it everywhere without duplicating the same code everywhere. Please let me know if you need further clarification on this.

**Comment by ymaheshwari1** [comment]
@Kajol-Kumari Yes we can do that. I will do the changes

**Comment by ymaheshwari1** [comment]
@Kajol-Kumari I have created another template for the message.

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for incorporating the changes @ymaheshwari1 
LGTM :)

**Comment by harsh-9in** [comment]
@diyajaiswal11 plz remove conflicts.

**Comment by harsh-9in** [comment]
@ymaheshwari1 plz remove conflicts then it is good to go.

**Comment by ymaheshwari1** [comment]
@harsh-9in Done

**Pull request merged**
