### PR TITLE
Logo_added

### PR DESCRIPTION
**Pull request by ritiksoni00**
image

Black-Texture

### CODE REVIEW

**Comment by ritiksoni00** [comment]
@Swarnimashukla and @Kajol-Kumari  ??

**Comment by Kajol-Kumari** [comment]
@ritiksoni00 I can see `contribution.md` file in this PR which has nothing to do with this PR. Please remove that file changes.

**Comment by ritiksoni00** [comment]
@Kajol-Kumari  anything else?

**Comment by Kajol-Kumari** [comment]
@ritiksoni00 `readme.md` change is still in this PR please revert it.

**Comment by Kajol-Kumari** [comment]
@ritiksoni00 you have completely messed up this PR. I recommend you to delete your forked repo, again fork it from main repo, make a fresh install on your local, add these images at their appropriate location and then make a new PR.

**Comment by ritiksoni00** [comment]
ohkay!! sorry i have some doubt will you help me ill share my screen ... i have tried a lot but not getting it

**Pull request closed without merging**
