### PR TITLE
Resolved Image issue #167

### PR DESCRIPTION
**Pull request by kritikaparmar-programmer**
Fixes: #167 

# Proposed Changes
 - Main Changes in settings.py and views.py
 
# Additional Info
  - Updated User profile pic
  
# Screenshots
profile_theek

### CODE REVIEW

**Comment by kritikaparmar-programmer** [comment]
Hey @harsh-9in I've done the changes.. Kindly review them
Also please delete this db.sqlite3 file as it is creating error I tried deleting  it bit was not able to ..

**Comment by kritikaparmar-programmer** [comment]
Ok I've done one more try.. Take a look now

**Comment by harsh-9in** [comment]
@Kajol-Kumari plz review this.

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@kritikaparmar-programmer I tried pulling your branch and verify the changes on my local but I am getting an error and not able to visit the home page of the site. Can you please verify and fix this on your end.

secondly please remove these .png files from this PR as we don't require it.

**Comment by kritikaparmar-programmer** [comment]
Ok @Kajol-Kumari I'm gonna make a new pr for this..

**Pull request closed without merging**
