### PR TITLE
added tests

### PR DESCRIPTION
**Pull request by chetak123**
# Related Issue or bug
  - test for blog

Fixes: #156 

# Proposed Changes
 - Added test scripts for urls,forms and models of blog app
 
# Additional Info
  - made 10 unit test for urls.py , 1 test for forms.py and 2 unit test for __str__ function of models.py
  
# Screenshots/Gif

new_peek

### CODE REVIEW

**Review by harsh-9in — COMMENTED** [review]
Awesome :rocket:

**Comment by harsh-9in** [comment]
are u a participent of DWOC or NWOC?

**Comment by chetak123** [comment]
DWOC sir

**Comment by harsh-9in** [comment]
okey

**Pull request merged**
