### PR TITLE
Removed sidebar and trending section

### PR DESCRIPTION
**Pull request by Akshi149**
Removed Sidebar and added header and footer

Fixes: #170 

# Screenshots

Annotation 2020-09-26 103416|

### CODE REVIEW

**Review by Kajol-Kumari — COMMENTED** [review]
@Akshi149 do we require the image files in this PR? If not please remove them.

**Comment by Akshi149** [comment]
@Kajol-Kumari these images (phone, address, mail) are actually used in footer

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari these images (phone, address, mail) are actually used in footer

Can't we use icons instead as images takes a lot of space and doesn't seem right to be used here.

**Comment by Akshi149** [comment]
okay lemme try it once 👍

**Comment by Akshi149** [comment]
@Kajol-Kumari  are the icons okay?


127 0 0 1_8000_post_create_ - Google Chrome 27-09-2020 13_10_18

**Review by Kajol-Kumari — COMMENTED** [review]
Better. Can we please keep the footer in a separate file and just render it whenever needed?

**Comment by Akshi149** [comment]
@Kajol-Kumari please have a look

**Review by Kajol-Kumari — APPROVED** [review]
LGTM now :+1: 
Thanks @Akshi149 for implementing the suggested changes.

**Review by harsh-9in — APPROVED** [review]

**Pull request merged**
