### PR TITLE
added comment feature

### PR DESCRIPTION
**Pull request by rutujadhanawade**
# Related Issuse or bug
  - Info about Issue or bug

Fixes: #160 

# Proposed Changes
- I have added a comment feature.
- one or more than one authenticated user can comment on the blog.

  
# Screenshots
SS1 (before login)
c4

SS2: (after login)
c1

SS3: (after comment)
c2

### CODE REVIEW

**Comment by rutujadhanawade** [comment]
@harsh-9in Please review this.!

**Review by Kajol-Kumari — COMMENTED** [review]
@rutujadhanawade can you please tell me why do we need `.idea/inspectionProfiles/Project_Default.xml` file?

**Comment by rutujadhanawade** [comment]
@Kajol-Kumari I use pycharm ide so idea folder automatically creates.
Should I delete that?

**Comment by Kajol-Kumari** [comment]
Hey @rutujadhanawade I think we can remove migration file as well as it will automatically get generated after runing the migration command.

**Comment by rutujadhanawade** [comment]
@Kajol-Kumari I have removed the migrations folder also .
Please review.

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Review by harsh-9in — APPROVED** [review]

**Pull request merged**
